import {
  ArmorDef,
  BlockDef,
  EmoteDef,
  ItemDef,
  MobDef,
  ProjectMeta,
  toClassName,
  toConstant
} from './utils'
import { ParsedProject } from './parser'

function pkgPath(pkg: string): string {
  return pkg.replace(/\./g, '/')
}

export function generateAllFiles(parsed: ParsedProject): Record<string, string> {
  const { meta, pkg, items, blocks, armors, mobs, emotes } = parsed
  const files: Record<string, string> = {}

  files['gradle.properties'] = generateGradleProperties(meta)
  files[`src/main/java/${pkgPath(pkg)}/${toClassName(meta.modId)}Mod.java`] = generateMainMod(
    parsed
  )
  files[`src/main/java/${pkgPath(pkg)}/ModItems.java`] = generateModItems(pkg, meta.modId, items, armors)
  files[`src/main/java/${pkgPath(pkg)}/ModBlocks.java`] = generateModBlocks(pkg, meta.modId, blocks)
  files[`src/main/java/${pkgPath(pkg)}/ModEntities.java`] = generateModEntities(pkg, meta.modId, mobs)
  files[`src/main/java/${pkgPath(pkg)}/ModParticles.java`] = generateModParticles(pkg, meta.modId)
  files[`src/main/java/${pkgPath(pkg)}/VisualEffects.java`] = generateVisualEffects(pkg)
  files[`src/main/java/${pkgPath(pkg)}/client/${toClassName(meta.modId)}ClientMod.java`] =
    generateClientMod(parsed)
  files[`src/main/java/${pkgPath(pkg)}/network/VisualCodingNetworking.java`] =
    generateNetworking(pkg, meta.modId)
  files[`src/main/java/${pkgPath(pkg)}/network/ScreenshakeHandler.java`] = generateScreenshakeHandler(pkg)
  files[`src/main/java/${pkgPath(pkg)}/emote/EmoteHandler.java`] = generateEmoteHandler(pkg)
  files[`src/main/java/${pkgPath(pkg)}/emote/EmoteRegistry.java`] = generateEmoteRegistry(pkg, emotes)
  files[`src/main/java/${pkgPath(pkg)}/emote/EmotePlayer.java`] = generateEmotePlayer(pkg, meta.modId)

  for (const item of items) {
    files[`src/main/java/${pkgPath(pkg)}/item/${item.className}.java`] = generateItemClass(pkg, item)
    files[`src/main/resources/assets/${meta.modId}/models/item/${item.id}.json`] = generateItemModel(
      meta.modId,
      item
    )
  }

  for (const block of blocks) {
    files[`src/main/java/${pkgPath(pkg)}/block/${block.className}.java`] = generateBlockClass(
      pkg,
      block
    )
    files[`src/main/resources/assets/${meta.modId}/blockstates/${block.id}.json`] = generateBlockstate(
      meta.modId,
      block
    )
    files[`src/main/resources/assets/${meta.modId}/models/block/${block.id}.json`] = generateBlockModel(
      meta.modId,
      block
    )
    files[`src/main/resources/assets/${meta.modId}/models/item/${block.id}.json`] =
      generateBlockItemModel(meta.modId, block)
  }

  for (const armor of armors) {
    files[`src/main/java/${pkgPath(pkg)}/item/${armor.className}.java`] = generateArmorClass(pkg, armor)
    files[`src/main/resources/assets/${meta.modId}/models/item/${armor.id}.json`] = generateItemModel(
      meta.modId,
      { id: armor.id, texture: armor.texture }
    )
  }

  for (const mob of mobs) {
    files[`src/main/java/${pkgPath(pkg)}/entity/${mob.className}.java`] = generateMobEntity(pkg, mob)
    files[`src/main/java/${pkgPath(pkg)}/client/renderer/${mob.className}Renderer.java`] =
      generateMobRenderer(pkg, mob)
    files[`src/main/java/${pkgPath(pkg)}/client/model/${mob.className}Model.java`] =
      generateMobModel(pkg, meta.modId, mob)
  }

  for (const emote of emotes) {
    files[`src/main/java/${pkgPath(pkg)}/emote/${toClassName(emote.id)}Emote.java`] = generateEmoteClass(
      pkg,
      emote
    )
  }

  files['src/main/resources/fabric.mod.json'] = generateFabricModJson(pkg, meta)
  files[`src/main/resources/assets/${meta.modId}/lang/en_us.json`] = generateLang(
    meta,
    items,
    blocks,
    armors,
    mobs,
    emotes
  )

  return files
}

function generateGradleProperties(meta: ProjectMeta): string {
  return `org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=26.2
yarn_mappings=26.2+build.1
loader_version=0.19.3
fabric_version=0.154.2+26.2
geckolib_version=5.5.1

mod_version=1.0.0
maven_group=com.visualcoding
archives_base_name=${meta.modId}

mod_id=${meta.modId}
mod_name=${meta.modName}
`
}

function generateFabricModJson(pkg: string, meta: ProjectMeta): string {
  return JSON.stringify(
    {
      schemaVersion: 1,
      id: meta.modId,
      version: '1.0.0',
      name: meta.modName,
      description: `Generated by VisualCoding for Minecraft ${meta.minecraftVersion}`,
      authors: ['VisualCoding'],
      license: 'MIT',
      environment: '*',
      entrypoints: {
        main: [`${pkg}.${toClassName(meta.modId)}Mod`],
        client: [`${pkg}.client.${toClassName(meta.modId)}ClientMod`]
      },
      depends: {
        fabricloader: '>=0.19.0',
        minecraft: '~26.2',
        java: '>=21',
        fabric: '*',
        geckolib: '*'
      }
    },
    null,
    2
  )
}

function generateLang(
  meta: ProjectMeta,
  items: ItemDef[],
  blocks: BlockDef[],
  armors: ArmorDef[],
  mobs: MobDef[],
  emotes: EmoteDef[]
): string {
  const lang: Record<string, string> = {}
  for (const item of items) lang[`item.${meta.modId}.${item.id}`] = item.name
  for (const block of blocks) lang[`block.${meta.modId}.${block.id}`] = block.name
  for (const armor of armors) lang[`item.${meta.modId}.${armor.id}`] = armor.name
  for (const mob of mobs) lang[`entity.${meta.modId}.${mob.id}`] = mob.name
  for (const emote of emotes) lang[`emote.${meta.modId}.${emote.id}`] = emote.name
  return JSON.stringify(lang, null, 2)
}

function generateMainMod(parsed: ParsedProject): string {
  const { pkg, meta, emotes, mobs } = parsed
  const className = `${toClassName(meta.modId)}Mod`
  const emoteRegistrations = emotes
    .map((e) => `        EmoteRegistry.register("${e.command}", new ${toClassName(e.id)}Emote());`)
    .join('\n')
  const attrRegs = mobs
    .map(
      (m) =>
        `        FabricDefaultAttributeRegistry.register(ModEntities.${toConstant(m.id)}, ${m.className}.createAttributes());`
    )
    .join('\n')

  return `package ${pkg};

import ${pkg}.emote.*;
import ${pkg}.network.VisualCodingNetworking;
import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.object.builder.v1.entity.FabricDefaultAttributeRegistry;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ${className} implements ModInitializer {
    public static final String MOD_ID = "${meta.modId}";
    public static final Logger LOGGER = LoggerFactory.getLogger(MOD_ID);

    @Override
    public void onInitialize() {
        ModItems.register();
        ModBlocks.register();
        ModEntities.register();
        ModParticles.register();
${attrRegs || '        // No mob attributes'}
        VisualCodingNetworking.registerServer();
${emoteRegistrations || '        // No emotes'}
${emotes.length ? '        EmoteRegistry.registerCommands();' : ''}

        LOGGER.info("${meta.modName} loaded!");
    }
}
`
}

function generateModItems(pkg: string, modId: string, items: ItemDef[], armors: ArmorDef[]): string {
  const itemRegs = items
    .map(
      (i) =>
        `        ${toConstant(i.id)} = Registry.register(BuiltInRegistries.ITEM, ResourceLocation.fromNamespaceAndPath(MOD_ID, "${i.id}"), new ${i.className}());`
    )
    .join('\n')
  const armorRegs = armors
    .map(
      (a) =>
        `        ${toConstant(a.id)} = Registry.register(BuiltInRegistries.ITEM, ResourceLocation.fromNamespaceAndPath(MOD_ID, "${a.id}"), new ${a.className}());`
    )
    .join('\n')
  const itemFields = items.map((i) => `    public static Item ${toConstant(i.id)};`).join('\n')
  const armorFields = armors.map((a) => `    public static Item ${toConstant(a.id)};`).join('\n')

  return `package ${pkg};

import ${pkg}.item.*;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;

public class ModItems {
    public static final String MOD_ID = ${toClassName(modId)}Mod.MOD_ID;
${itemFields}
${armorFields}

    public static void register() {
${itemRegs || '        // No items'}
${armorRegs || '        // No armor'}
    }
}
`
}

function generateItemClass(pkg: string, item: ItemDef): string {
  const useMethod =
    item.rightClickActions.length > 0
      ? `
    @Override
    public InteractionResult use(Level world, Player player, InteractionHand hand) {
        if (!world.isClientSide()) {
${item.rightClickActions.join('\n')}
        }
        return InteractionResult.SUCCESS;
    }`
      : ''

  return `package ${pkg}.item;

import net.minecraft.network.chat.Component;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.sounds.SoundSource;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.InteractionResult;
import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.Level;
import ${pkg}.ModParticles;
import ${pkg}.VisualEffects;

public class ${item.className} extends Item {
    public ${item.className}() {
        super(new Item.Properties());
    }
${useMethod}
}
`
}

function generateModBlocks(pkg: string, modId: string, blocks: BlockDef[]): string {
  const regs = blocks
    .map(
      (b) =>
        `        ${toConstant(b.id)} = Registry.register(BuiltInRegistries.BLOCK, ResourceLocation.fromNamespaceAndPath(MOD_ID, "${b.id}"), new ${b.className}());`
    )
    .join('\n')
  const fields = blocks.map((b) => `    public static Block ${toConstant(b.id)};`).join('\n')

  return `package ${pkg};

import ${pkg}.block.*;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.block.Block;

public class ModBlocks {
    public static final String MOD_ID = ${toClassName(modId)}Mod.MOD_ID;
${fields}

    public static void register() {
${regs || '        // No blocks'}
    }
}
`
}

function generateBlockClass(pkg: string, block: BlockDef): string {
  const useMethod =
    block.interactActions.length > 0
      ? `
    @Override
    protected InteractionResult useWithoutItem(BlockState state, Level world, BlockPos pos, Player player, BlockHitResult hit) {
        if (!world.isClientSide()) {
${block.interactActions.join('\n')}
        }
        return InteractionResult.SUCCESS;
    }`
      : ''

  return `package ${pkg}.block;

import net.minecraft.core.BlockPos;
import net.minecraft.network.chat.Component;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.sounds.SoundSource;
import net.minecraft.world.InteractionResult;
import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.phys.BlockHitResult;
import ${pkg}.ModParticles;
import ${pkg}.VisualEffects;

public class ${block.className} extends Block {
    public ${block.className}() {
        super(BlockBehaviour.Properties.of().strength(${block.hardness}f));
    }
${useMethod}
}
`
}

function generateModEntities(pkg: string, modId: string, mobs: MobDef[]): string {
  const regs = mobs
    .map(
      (m) =>
        `        ${toConstant(m.id)} = Registry.register(BuiltInRegistries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(MOD_ID, "${m.id}"),
            EntityType.Builder.of(${m.className}::new, MobCategory.MONSTER).sized(0.9f, 1.8f).build("${m.id}"));`
    )
    .join('\n')
  const fields = mobs.map((m) => `    public static EntityType<${m.className}> ${toConstant(m.id)};`).join('\n')

  return `package ${pkg};

import ${pkg}.entity.*;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.MobCategory;

public class ModEntities {
    public static final String MOD_ID = ${toClassName(modId)}Mod.MOD_ID;
${fields}

    public static void register() {
${regs || '        // No mobs'}
    }
}
`
}

function generateMobEntity(pkg: string, mob: MobDef): string {
  const goals: string[] = []
  if (mob.ai.wander) goals.push('        this.goalSelector.addGoal(5, new RandomStrollGoal(this, 1.0));')
  goals.push('        this.goalSelector.addGoal(2, new MeleeAttackGoal(this, 1.0, false));')
  goals.push('        this.targetSelector.addGoal(2, new NearestAttackableTargetGoal<>(this, Player.class, true));')

  return `package ${pkg}.entity;

import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.ai.attributes.AttributeSupplier;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.entity.ai.goal.*;
import net.minecraft.world.entity.monster.Monster;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.level.Level;
import software.bernie.geckolib.animatable.GeoEntity;
import software.bernie.geckolib.animatable.instance.AnimatableInstanceCache;
import software.bernie.geckolib.animation.*;
import software.bernie.geckolib.util.GeckoLibUtil;

public class ${mob.className} extends Monster implements GeoEntity {
    private final AnimatableInstanceCache cache = GeckoLibUtil.createInstanceCache(this);
    private boolean attacking = false;

    public ${mob.className}(EntityType<? extends Monster> type, Level world) {
        super(type, world);
    }

    public static AttributeSupplier.Builder createAttributes() {
        return Monster.createMonsterAttributes()
            .add(Attributes.MAX_HEALTH, ${mob.health})
            .add(Attributes.MOVEMENT_SPEED, ${mob.speed})
            .add(Attributes.ATTACK_DAMAGE, ${mob.damage});
    }

    @Override
    protected void registerGoals() {
${goals.join('\n')}
    }

    @Override
    public void tick() {
        super.tick();
        if (this.swinging) attacking = true;
        else if (attacking && !this.swinging) attacking = false;
    }

    public boolean isAttackingAnim() {
        return attacking;
    }

    @Override
    public void registerControllers(AnimatableManager.ControllerRegistrar controllers) {
        controllers.add(new AnimationController<>(this, "controller", 0, state -> {
            if (isAttackingAnim()) return state.setAndContinue(RawAnimation.begin().thenLoop("${mob.anims.attack}"));
            if (getDeltaMovement().horizontalDistanceSqr() > 1.0E-6) return state.setAndContinue(RawAnimation.begin().thenLoop("${mob.anims.walk}"));
            return state.setAndContinue(RawAnimation.begin().thenLoop("${mob.anims.idle}"));
        }));
    }

    @Override
    public AnimatableInstanceCache getAnimatableInstanceCache() {
        return cache;
    }
}
`
}

function generateMobModel(pkg: string, modId: string, mob: MobDef): string {
  return `package ${pkg}.client.model;

import ${pkg}.entity.${mob.className};
import net.minecraft.resources.ResourceLocation;
import software.bernie.geckolib.model.GeoModel;

public class ${mob.className}Model extends GeoModel<${mob.className}> {
    @Override
    public ResourceLocation getModelResource(${mob.className} animatable) {
        return ResourceLocation.fromNamespaceAndPath("${modId}", "${mob.geo}");
    }

    @Override
    public ResourceLocation getTextureResource(${mob.className} animatable) {
        return ResourceLocation.fromNamespaceAndPath("${modId}", "${mob.texture}");
    }

    @Override
    public ResourceLocation getAnimationResource(${mob.className} animatable) {
        return ResourceLocation.fromNamespaceAndPath("${modId}", "${mob.animations}");
    }
}
`
}

function generateMobRenderer(pkg: string, mob: MobDef): string {
  return `package ${pkg}.client.renderer;

import ${pkg}.client.model.${mob.className}Model;
import ${pkg}.entity.${mob.className};
import net.minecraft.client.renderer.entity.EntityRendererProvider;
import software.bernie.geckolib.renderer.GeoEntityRenderer;

public class ${mob.className}Renderer extends GeoEntityRenderer<${mob.className}> {
    public ${mob.className}Renderer(EntityRendererProvider.Context context) {
        super(context, new ${mob.className}Model());
    }
}
`
}

function generateArmorClass(pkg: string, armor: ArmorDef): string {
  return `package ${pkg}.item;

import net.minecraft.world.item.ArmorItem;
import net.minecraft.world.item.ArmorMaterials;
import net.minecraft.world.item.Item;

public class ${armor.className} extends ArmorItem {
    public ${armor.className}() {
        super(ArmorMaterials.IRON, ArmorItem.Type.${armor.slot}, new Item.Properties());
    }
}
`
}

function generateClientMod(parsed: ParsedProject): string {
  const { pkg, meta, mobs } = parsed
  const entityRenderers = mobs
    .map(
      (m) =>
        `        EntityRendererRegistry.register(ModEntities.${toConstant(m.id)}, ${m.className}Renderer::new);`
    )
    .join('\n')

  return `package ${pkg}.client;

import ${pkg}.ModEntities;
import ${pkg}.ModParticles;
import ${pkg}.client.renderer.*;
import ${pkg}.network.VisualCodingNetworking;
import net.fabricmc.api.ClientModInitializer;
import net.fabricmc.fabric.api.client.rendering.v1.EntityRendererRegistry;

public class ${toClassName(meta.modId)}ClientMod implements ClientModInitializer {
    @Override
    public void onInitializeClient() {
${entityRenderers || '        // No mob renderers'}
        VisualCodingNetworking.registerClient();
        ModParticles.registerClient();
    }
}
`
}

function generateModParticles(pkg: string, modId: string): string {
  return `package ${pkg};

import net.fabricmc.fabric.api.particle.v1.FabricParticleTypes;
import net.minecraft.core.Registry;
import net.minecraft.core.particles.SimpleParticleType;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;

public class ModParticles {
    public static SimpleParticleType SPARK;

    public static void register() {
        SPARK = Registry.register(BuiltInRegistries.PARTICLE_TYPE,
            ResourceLocation.fromNamespaceAndPath("${modId}", "spark"),
            FabricParticleTypes.simple());
    }

    public static void registerClient() {}
}
`
}

function generateVisualEffects(pkg: string): string {
  return `package ${pkg};

import ${pkg}.network.VisualCodingNetworking;
import net.minecraft.core.BlockPos;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.level.Level;
import net.minecraft.core.particles.SimpleParticleType;

public final class VisualEffects {
    private VisualEffects() {}

    public static void spawnParticles(Level world, BlockPos pos, SimpleParticleType particle, int count) {
        if (world.isClientSide()) return;
        for (int i = 0; i < count; i++) {
            world.sendParticles(particle, pos.getX() + 0.5, pos.getY() + 1.0, pos.getZ() + 0.5, 1, 0.2, 0.2, 0.2, 0.05);
        }
    }

    public static void shakeScreen(Player player, float intensity, float duration) {
        if (player instanceof ServerPlayer serverPlayer) {
            VisualCodingNetworking.sendScreenshake(serverPlayer, intensity, duration);
        }
    }
}
`
}

function generateNetworking(pkg: string, modId: string): string {
  const modClass = `${toClassName(modId)}Mod`
  return `package ${pkg}.network;

import ${pkg}.${modClass};
import net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking;
import net.fabricmc.fabric.api.networking.v1.PacketByteBufs;
import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking;
import net.minecraft.network.FriendlyByteBuf;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerPlayer;

public class VisualCodingNetworking {
    public static final ResourceLocation SCREENSHAKE = ResourceLocation.fromNamespaceAndPath(${modClass}.MOD_ID, "screenshake");

    public static void registerServer() {}

    public static void registerClient() {
        ClientPlayNetworking.registerGlobalReceiver(SCREENSHAKE, (client, handler, buf, responseSender) -> {
            float intensity = buf.readFloat();
            float duration = buf.readFloat();
            client.execute(() -> ScreenshakeHandler.shake(intensity, duration));
        });
    }

    public static void sendScreenshake(ServerPlayer player, float intensity, float duration) {
        FriendlyByteBuf buf = PacketByteBufs.create();
        buf.writeFloat(intensity);
        buf.writeFloat(duration);
        ServerPlayNetworking.send(player, SCREENSHAKE, buf);
    }
}
`
}

function generateScreenshakeHandler(pkg: string): string {
  return `package ${pkg}.network;

import net.minecraft.client.Minecraft;

public final class ScreenshakeHandler {
    private static float intensity;
    private static float timeLeft;

    private ScreenshakeHandler() {}

    public static void shake(float power, float seconds) {
        intensity = power;
        timeLeft = seconds;
    }

    public static float getIntensity() {
        if (timeLeft <= 0) return 0;
        timeLeft -= Minecraft.getInstance().getDeltaTracker().getGameTimeDeltaPartialTick(false) / 20f;
        return Math.max(0, intensity * (timeLeft > 0 ? 1 : 0));
    }
}
`
}

function generateEmoteHandler(pkg: string): string {
  return `package ${pkg}.emote;

import net.minecraft.server.level.ServerPlayer;

public interface EmoteHandler {
    String getAnimation();
    float getDuration();
    boolean lockMovement();
    void play(ServerPlayer player);
}
`
}

function generateEmoteRegistry(pkg: string, emotes: EmoteDef[]): string {
  return `package ${pkg}.emote;

import com.mojang.brigadier.arguments.StringArgumentType;
import net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback;
import net.minecraft.commands.Commands;
import net.minecraft.network.chat.Component;
import net.minecraft.server.level.ServerPlayer;

import java.util.HashMap;
import java.util.Map;

public final class EmoteRegistry {
    private static final Map<String, EmoteHandler> EMOTES = new HashMap<>();

    private EmoteRegistry() {}

    public static void register(String command, EmoteHandler handler) {
        EMOTES.put(command.toLowerCase(), handler);
    }

    public static void registerCommands() {
        CommandRegistrationCallback.EVENT.register((dispatcher, registry, env) -> {
            dispatcher.register(Commands.literal("emote")
                .then(Commands.argument("name", StringArgumentType.string())
                    .executes(ctx -> {
                        ServerPlayer player = ctx.getSource().getPlayerOrException();
                        String name = StringArgumentType.getString(ctx, "name").toLowerCase();
                        EmoteHandler emote = EMOTES.get(name);
                        if (emote == null) {
                            ctx.getSource().sendFailure(Component.literal("Unknown emote: " + name));
                            return 0;
                        }
                        emote.play(player);
                        return 1;
                    })));
        });
    }
}
`
}

function generateEmotePlayer(pkg: string, modId: string): string {
  return `package ${pkg}.emote;

import ${pkg}.network.VisualCodingNetworking;
import net.minecraft.network.chat.Component;
import net.minecraft.server.level.ServerPlayer;

public final class EmotePlayer {
    private EmotePlayer() {}

    public static void play(ServerPlayer player, EmoteHandler emote) {
        player.sendSystemMessage(Component.literal("Playing emote: " + emote.getAnimation()));
        // Animation sync hooks can be extended with GeckoLib player animations
    }
}
`
}

function generateEmoteClass(pkg: string, emote: EmoteDef): string {
  return `package ${pkg}.emote;

import net.minecraft.server.level.ServerPlayer;

public class ${toClassName(emote.id)}Emote implements EmoteHandler {
    @Override
    public String getAnimation() {
        return "${emote.animation}";
    }

    @Override
    public float getDuration() {
        return ${emote.duration}f;
    }

    @Override
    public boolean lockMovement() {
        return ${emote.lockMovement};
    }

    @Override
    public void play(ServerPlayer player) {
        EmotePlayer.play(player, this);
    }
}
`
}

function generateItemModel(modId: string, item: { id: string; texture: string }): string {
  const texId = item.texture.replace(/^textures\//, '').replace(/\.png$/, '')
  return JSON.stringify(
    { parent: 'minecraft:item/generated', textures: { layer0: `${modId}:${texId}` } },
    null,
    2
  )
}

function generateBlockstate(modId: string, block: BlockDef): string {
  return JSON.stringify({ variants: { '': { model: `${modId}:block/${block.id}` } } }, null, 2)
}

function generateBlockModel(modId: string, block: BlockDef): string {
  const texId = block.texture.replace(/^textures\//, '').replace(/\.png$/, '')
  return JSON.stringify(
    { parent: 'minecraft:block/cube_all', textures: { all: `${modId}:${texId}` } },
    null,
    2
  )
}

function generateBlockItemModel(modId: string, block: BlockDef): string {
  return JSON.stringify({ parent: `${modId}:block/${block.id}` }, null, 2)
}
